; Legacy root PlatformIO entrypoint.
; Primaerer Wokwi-Pfad fuer V2: .\v2\wokwi\

[platformio]
default_envs = esp32doit-devkit-v1
src_dir = src

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
extra_scripts = post:tools/pio_post_copy.py

lib_deps =
  bogde/HX711 @ ^0.7.5
  marcoschwartz/LiquidCrystal_I2C @ ^1.1.4

build_flags =
  -D DEBUG_LEVEL=5

build_src_filter =
  +<*>
  -<*.chip.c>
  -<wokwi-api.h>

monitor_filters = esp32_exception_decoder
check_tool = cppcheck
check_skip_packages = yes
check_flags =
  cppcheck: --suppress=unusedFunction:src/main.cpp
check_src_filters =
  +<src/>
  +<include/>

[env:esp32doit-devkit-v1]
board = esp32doit-devkit-v1
build_flags =
  ${env.build_flags}
  -D WOKWI_SIM=1

[env:esp32doit-devkit-v1-hw]
board = esp32doit-devkit-v1
build_flags =
  ${env.build_flags}
